apiVersion: apps/v1
kind: Deployment
metadata:
  name: gusapp
  labels:
    app: gusapp
    key: gusapp
spec:
  replicas: 1
  selector:
    matchLabels:
      key: gusapp
  template:
    metadata:
      labels:
        key: gusapp
        app: gusapp
    spec:
      volumes:
        - name: config
          configMap:
            name: gusapp-family
            items:
              - key: members
                path: "family.txt"
      containers:
        - name: gusapp
          # image: "wesleywillians/hello-go:v9.6" #"guuhworship/gogus:v2" 
          image: "guuhworship/gogus:v2" 
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 30
            # initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            # initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
              # readiness e quando a aplicacao esta pronta para receber trafego
            periodSeconds: 3
            failureThreshold: 1
            # initialDelaySeconds: 10
          envFrom:
            - configMapRef:
                name: gusapp-env
            - secretRef:
                name: gusapp-secret
          volumeMounts:
            - mountPath: "/myfamily"
              name: config
          resources: # minimo que precisa para rodar
            limits: #ate onde esse pode utilizar de recursos (reservando recursos do cluster)
              memory: "25Mi" # 1Gi = 1024Mi se tivesse 3 replicas de 512Mi seria 1536Mi
              cpu: "0.05" #cluster com finito 3vcpus (3000 milicores) faca o calculo usando limites e nao o minimo
            requests: # MINIMO QUE PRECISA PARA RODAR (reservando recursos do cluster)
              memory: "20Mi" # 1Gi = 1024Mi se tivesse 3 replicas de 512Mi seria 1536Mi
              cpu: "0.05"  #vCPU quanto mais compra mais poder de processamento 1000m (milicores) 500m significa que usara a metade.  0.5 significa que vai usar a metade
