apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gusapp-hpa
  labels:
    app: gusapp
    key: gusapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gusapp
  minReplicas: 1 #na pratica o minimo sao duas replicas
  maxReplicas: 5 # maximo de replicas 
  targetCPUUtilizationPercentage: 30 #quando chegar a 30% de uso de cpu, o hpa vai aumentar o numero de replicas geralmente usar 70% de uso de cpu
  # metrics:
  #   - type: Resource
  #     resource:
  #       name: cpu
  #       target:
  #         type: Utilization
  #         averageUtilization: 50
  # metrics:
  #   - type: Pods
  #     pods:
  #       metric:
  #         name: http_requests_per_second
  #       target:
  #         type: AverageValue
  #         averageValue: "1000"