kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# https://kind.sigs.k8s.io/docs/user/configuration/#cluster-wide-options
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker